### ISSUE TITLE
Groups page need empty states

### ISSUE THREAD

**Issue by johnCbogil** [johnCbogil/voices-ios#13]

**Comment by dknomura** [comment]
Branch master, branch name- #13- group zerostate

**Comment by johnCbogil** [comment]
Hey @dknomura, the 'My Groups' page in the app needs to display a zero state for when the user has not followed any groups. 

Please pull the latest version of Master and branch off of that. Please name the new branch "13-groupZeroState". 

Here are some examples of zero states if you are curious: http://emptystat.es/

Just create a red square or something temporary to represent the zerostate, the goal for now is just to get the logic working.
