### ISSUE TITLE
FEATURE: Buttons should not be pressable when the keyboard is open

### ISSUE THREAD

**Issue by johnCbogil** [johnCbogil/voices-ios#156]
For example, if the keyboard is open and you press the email button, the keyboard should hide, but nothing else should happen. The email composer should not appear.

**Comment by johnCbogil** [comment]
http://stackoverflow.com/questions/5306240/iphone-dismiss-keyboard-when-touching-outside-of-uitextfield

**Comment by JSahli** [comment]
Tried to find a way to only dismiss the keyboard without responding to the button touches. Didn't find any simple methods for it. The most elegant solution I had was to make an invisible view appear on top of all UI when the keyboard appears. The view responds to the tap gesture by dismissing the keyboard as well as itself. also the view will be removed if the keyboard is dismissed by finishing a search query(search/return) and not only from the tap gesture.

**Comment by johnCbogil** [comment]
Merged woot
