### ISSUE TITLE
Add governors to state reps

### ISSUE THREAD

**Issue by johnCbogil** [johnCbogil/voices-ios#20]

**Comment by johnCbogil** [comment]
Hey @krishnascoding, go ahead and create a pull request when you want me to take a look at it. (I could also download your branch to see how it looks but a pull request shows me exactly what files/lines of code changed).

Just a heads up, I didn't give the app a thorough QA but I did notice that the app crashes when the user tries to email a governor with the email missing. I noticed it with the Governor of Delaware. I started adding the emails to the google doc. Not sure if I'll be able to get all 50 emails so we need to make sure the app can handle missing data.

Thanks!

**Comment by johnCbogil** [comment]
Update: I added all the emails I could find. I only got about 40 of them so the app definitely needs to be able to handle missing data. Please update the app to include the latest csv file.

**Comment by krishnascoding** [comment]
Hey @johnCbogil I pushed the updated version of the app with Governors. It handles nil emails and has the updated governors list.
