### ISSUE TITLE
DESIGN: Remove "take action" from webview back button

### ISSUE THREAD

**Issue by johnCbogil** [johnCbogil/voices-ios#226]
I opened up a link inside one of the actions (ACLU has an action with a link) and the app opens the web view. Problem is that the viewcontroller title is "take action" and the back button title is also "take action". So it says "take action" twice. Please remove the "take action" text from the back button inside of the webview.

**Comment by ptclou** [comment]
This issue has been solved by creating an empty string back button (which also centered the title in the nav bar).

**Comment by johnCbogil** [comment]
@ptcloutier Sweet send over a pr when youre ready!

**Comment by johnCbogil** [comment]
closed this by accident
