### ISSUE TITLE
BUG: App crashes on Firebase followGroup: method

### ISSUE THREAD

**Issue by ptclou** [johnCbogil/voices-ios#466]
A crash occurs upon opening the app when it's the first run. 
To recreate you must first reinstall Voices on the home screen in the simulator. 
Make a breakpoint in FirebaseManager.m at line 93. That's where the nil pointer crash occurs.
This method is called in the AppDelegate, in handleDynamicLink: method.

**Comment by johnCbogil** [comment]
Hey @ptcloutier I'm not able to reproduce on sim or device, i'm on the develop branch. Is this only happening when installed via deeplink? Any other info you could provide?

**Comment by ptclou** [comment]
I also was unable to reproduce this crash today.

**Comment by johnCbogil** [comment]
Great
