### ISSUE TITLE
BUG: Action tableview still has phantom actions from J4A

### ISSUE THREAD

**Issue by ptclou** [johnCbogil/voices-ios#468]
Phantom actions were being left in the actions tableView. When a user would follow and then unfollow a group, the actions should disappear from the followed actions. This was being caused by the Jobs For America group having actions in its list that have several different groupKeys belonging to other groups amongst a bunch of test actions with placeholder names. I think this might be a backend issue since that's where the actions originate.

**Comment by johnCbogil** [comment]
Can you be more specific @ptcloutier ? actions can't have more than one groupKey but it's possible that multiple groups have the same actions (by accident). So like LWV and ACLU could accidentally both have action 46. Is that what's occurring?

**Comment by ptclou** [comment]
Here is a more detailed account of the bug I observed. 
When a user follows the group, Jobs For America, the user's list of followed actions is populated with 28 actions, 7 of which contain the groupKeys, LWV, LWVWI, and ESHV. These actions shouldn't be associated with this group:

<img width="371" alt="actionlist" src="https://user-images.githubusercontent.com/15159970/26937353-2302c41a-4c3f-11e7-843d-f20961f87dbc.png">

Here we observe the current user's followed groups: Jobs For America, and the 
list of actions with disparate groupKeys:

<img width="946" alt="debugger" src="https://user-images.githubusercontent.com/15159970/26937367-2ba7ed3e-4c3f-11e7-9690-285e3cd4deb3.png">

The groupKey must match the assumed group so that the actions can be removed when a user unfollows the group. After the J4A group is unfollowed:

<img width="979" alt="debugger_unfollowed" src="https://user-images.githubusercontent.com/15159970/26937479-78c9cde4-4c3f-11e7-9bfa-6c2bd3dbd7cd.png">

The actions list after J4A is unfollowed still shows phantom actions: 

<img width="373" alt="phantoms" src="https://user-images.githubusercontent.com/15159970/26937559-b57638d6-4c3f-11e7-8df5-3b4fed438309.png">

**Comment by johnCbogil** [comment]
Ok awesome, i'll take a look at this info, this should help
