### ISSUE TITLE
FEATURE: The URL's listed in the groupDetail should just say "visit website"

### ISSUE THREAD

**Issue by johnCbogil** [johnCbogil/voices-ios#548]

**Comment by emiclark** [comment]
just getting clarification: 
you want the url to be replaced by: "visit website". pls see picture.
![548-visit website](https://user-images.githubusercontent.com/10621575/30559718-92285e7e-9c83-11e7-9402-092c86f3f4b4.png)

**Comment by johnCbogil** [comment]
Let's talk on slack before you start this ticket

**Comment by johnCbogil** [comment]
You can work on this ticket when you are ready @emiclark. And yes, please replace the URL with "Visit website".
